import os

from color_utils import sanitize_color


def apply(home, colors):
    bg = colors["bg"]
    fg = colors["fg"]
    bgSecondary = colors["bgSecondary"]
    bgTertiary = colors.get("bgTertiary", bgSecondary)
    bgAccent = colors.get("bgAccent", bgSecondary)
    accent = colors["accent"]
    accentComplementary = colors["accentComplementary"]
    muted = colors["muted"]
    border = colors["border"]

    btop_theme = f"""# Generated by Quickshell Theme service
theme[main_bg]="{sanitize_color(bg)}"
theme[main_fg]="{sanitize_color(fg)}"
theme[title]="{sanitize_color(fg)}"
theme[hi_fg]="{sanitize_color(accent)}"
theme[selected_bg]="{sanitize_color(bgAccent)}"
theme[selected_fg]="{sanitize_color(accent)}"
theme[inactive_fg]="{sanitize_color(muted)}"
theme[graph_text]="{sanitize_color(muted)}"
theme[meter_bg]="{sanitize_color(bgTertiary)}"
theme[proc_misc]="{sanitize_color(accentComplementary)}"
theme[cpu_box]="{sanitize_color(border)}"
theme[mem_box]="{sanitize_color(border)}"
theme[net_box]="{sanitize_color(border)}"
theme[proc_box]="{sanitize_color(border)}"
theme[div_line]="{sanitize_color(border)}"
theme[temp_start]="{sanitize_color(accentComplementary)}"
theme[temp_mid]="{sanitize_color(accent)}"
theme[temp_end]="{sanitize_color(accentComplementary)}"
theme[cpu_start]="{sanitize_color(accent)}"
theme[cpu_mid]="{sanitize_color(accent)}"
theme[cpu_end]="{sanitize_color(accentComplementary)}"
theme[free_start]="{sanitize_color(accent)}"
theme[free_mid]="{sanitize_color(accent)}"
theme[free_end]="{sanitize_color(accent)}"
theme[cached_start]="{sanitize_color(muted)}"
theme[cached_mid]="{sanitize_color(muted)}"
theme[cached_end]="{sanitize_color(muted)}"
theme[available_start]="{sanitize_color(accent)}"
theme[available_mid]="{sanitize_color(accent)}"
theme[available_end]="{sanitize_color(accent)}"
theme[used_start]="{sanitize_color(accentComplementary)}"
theme[used_mid]="{sanitize_color(accentComplementary)}"
theme[used_end]="{sanitize_color(accentComplementary)}"
theme[download_start]="{sanitize_color(accent)}"
theme[download_mid]="{sanitize_color(accent)}"
theme[download_end]="{sanitize_color(accent)}"
theme[upload_start]="{sanitize_color(accentComplementary)}"
theme[upload_mid]="{sanitize_color(accentComplementary)}"
theme[upload_end]="{sanitize_color(accentComplementary)}"
"""
    btop_theme_dir = os.path.join(home, ".config", "btop", "themes")
    os.makedirs(btop_theme_dir, exist_ok=True)
    with open(os.path.join(btop_theme_dir, "quickshell.theme"), "w") as f2:
        f2.write(btop_theme)

    btop_conf = os.path.join(home, ".config", "btop", "btop.conf")
    if os.path.exists(btop_conf):
        os.system(
            f"sed -i 's/^color_theme = .*/color_theme = \"quickshell\"/' '{btop_conf}'"
        )
