import os
import subprocess

from color_utils import hypr_color


def apply(home, colors):
    bg = colors["bg"]
    border = colors["border"]
    accent = colors["accent"]
    accentComplementary = colors["accentComplementary"]
    muted = colors["muted"]
    shadow = colors["shadow"]
    bgSecondary = colors["bgSecondary"]
    bgTertiary = colors.get("bgTertiary", bgSecondary)
    bgAccent = colors.get("bgAccent", accent)
    bgAccentComplementary = colors.get("bgAccentComplementary", accentComplementary)

    hypr_shadow_color = hypr_color(
        shadow, "73" if len(str(shadow).lstrip("#")) <= 6 else ""
    )
    hypr_content = f"""-- Generated by Quickshell Theme service
return {{
  bg = "{hypr_color(bg)}",
  border = "{hypr_color(border)}",
  border_alpha = "{hypr_color(border, "aa")}",
  accent = "{hypr_color(accent)}",
  accent_alpha = "{hypr_color(accent, "ee")}",
  accent_complementary = "{hypr_color(accentComplementary)}",
  accent_complementary_alpha = "{hypr_color(accentComplementary, "ee")}",
  bg_secondary = "{hypr_color(bgSecondary)}",
  bg_tertiary = "{hypr_color(bgTertiary)}",
  bg_accent = "{hypr_color(bgAccent)}",
  bg_accent_complementary = "{hypr_color(bgAccentComplementary)}",
  muted = "{hypr_color(muted)}",
  shadow = "{hypr_shadow_color}",
}}
"""
    hypr_conf_content = f"""# Generated by Quickshell Theme service
$bg = {hypr_color(bg)}
$border = {hypr_color(border)}
$border_alpha = {hypr_color(border, "aa")}
$accent = {hypr_color(accent)}
$accent_alpha = {hypr_color(accent, "ee")}
$accent_complementary = {hypr_color(accentComplementary)}
$accent_complementary_alpha = {hypr_color(accentComplementary, "ee")}
$bg_secondary = {hypr_color(bgSecondary)}
$bg_tertiary = {hypr_color(bgTertiary)}
$bg_accent = {hypr_color(bgAccent)}
$bg_accent_complementary = {hypr_color(bgAccentComplementary)}
$muted = {hypr_color(muted)}
$muted_alpha = {hypr_color(muted, "aa")}
"""
    hypr_dir = os.path.join(home, ".config", "hypr")
    os.makedirs(hypr_dir, exist_ok=True)
    with open(os.path.join(hypr_dir, "colors.lua"), "w") as f2:
        f2.write(hypr_content)
    with open(os.path.join(hypr_dir, "colors.conf"), "w") as f2:
        f2.write(hypr_conf_content)
    subprocess.run(
        ["hyprctl", "reload"], stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL
    )
