-- Generated by Quickshell Theme service
return {
  border = "rgb(2a2a2d)",
  border_alpha = "rgba(2a2a2daa)",
  accent = "rgb(58a2d9)",
  accent_alpha = "rgba(58a2d9ee)",
  shadow = "rgba(00000073)",
}
