format = """
$username$directory $git_branch$git_status
$character
"""

command_timeout = 5001
add_newline = false
palette = "quickshell"

[username]
style_user = "fg:bg bold bg:accent bold"
style_root = "bg bold"
format = "[](bold fg:accent)[$user]($style)[ ](bold fg:accent)"
disabled = false
show_always = true

[directory]
style = "bg:accent fg:bg"
format = '󰜥 [](bold fg:accent)[󰉋 $path]($style)[](bold fg:accent)'

[character]
success_symbol = "[](bold fg:accent)"
error_symbol = "[](bold fg:accentComplementary)"

[git_branch]
style = "bg: accent"
symbol = "󰘬"
truncation_length = 13
truncation_symbol = ""
format = "[](bold fg:accent)[$symbol $branch(:$remote_branch)](fg:bg bg:accent)[ ](bold fg:accent)"
