import os
import subprocess

from color_utils import hypr_color


def apply(home, colors):
    border = colors["border"]
    accent = colors["accent"]
    shadow = colors["shadow"]

    hypr_shadow_color = hypr_color(
        shadow, "73" if len(str(shadow).lstrip("#")) <= 6 else ""
    )
    hypr_content = f"""-- Generated by Quickshell Theme service
return {{
  border = "{hypr_color(border)}",
  border_alpha = "{hypr_color(border, "aa")}",
  accent = "{hypr_color(accent)}",
  accent_alpha = "{hypr_color(accent, "ee")}",
  shadow = "{hypr_shadow_color}",
}}
"""
    hypr_dir = os.path.join(home, ".config", "hypr")
    os.makedirs(hypr_dir, exist_ok=True)
    with open(os.path.join(hypr_dir, "colors.lua"), "w") as f2:
        f2.write(hypr_content)
    subprocess.run(
        ["hyprctl", "reload"], stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL
    )
