[general]
bars = 36
framerate = 60

[smoothing]
monstercat = 1
noise_reduction = 65
gravity = 100

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
